package iti.jets.persistence.model;
// Generated Sep 2, 2024, 5:22:05 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.Column;
import jakarta.persistence.Embeddable;

/**
 * CartItemId generated by hbm2java
 */
@Embeddable
public class CartItemId  implements java.io.Serializable {


     private int customerId;
     private int productId;

    public CartItemId() {
    }

    public CartItemId(int customerId, int productId) {
       this.customerId = customerId;
       this.productId = productId;
    }
   


    @Column(name="customer_id", nullable=false)
    public int getCustomerId() {
        return this.customerId;
    }
    
    public void setCustomerId(int customerId) {
        this.customerId = customerId;
    }


    @Column(name="product_id", nullable=false)
    public int getProductId() {
        return this.productId;
    }
    
    public void setProductId(int productId) {
        this.productId = productId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof CartItemId) ) return false;
		 CartItemId castOther = ( CartItemId ) other; 
         
		 return (this.getCustomerId()==castOther.getCustomerId())
 && (this.getProductId()==castOther.getProductId());
   }
   
   public int hashCode() {
         int result = 17;
         
        result = 37 * result + this.getCustomerId();
        result = 37 * result + this.getProductId();
         return result;
   }   


}


