package iti.jets.persistence.model;
// Generated Sep 2, 2024, 5:22:05 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

import java.util.HashSet;
import java.util.Set;

/**
 * Category generated by hbm2java
 */
@Entity
@Table(name="category"
    ,catalog="shomya"
)
public class Category  implements java.io.Serializable {


     private int id;
     private String name;
     private byte[] image;
     private boolean isDeleted = false;
     private Set<Customer> customers = new HashSet<Customer>(0);
     private Set<Product> products = new HashSet<Product>(0);

    public Category(){}
    public Category(String name, byte[] image) {
       this.name = name;
       this.image = image;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }


    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, unique = true)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="image")
    @Lob
    public  byte[] getImage() {
        return this.image;
    }
    
    public void setImage(byte[] image) {
        this.image = image;
    }

    @Column(name = "is_deleted", nullable = false)
    public boolean isDeleted() {
        return isDeleted;
    }

    public void setDeleted(boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="customer_has_interests_category", catalog="shomya", joinColumns = { 
        @JoinColumn(name="category_id", nullable=false) }, inverseJoinColumns = {
        @JoinColumn(name="customer_id", nullable=false) })
    public Set<Customer> getCustomers() {
        return this.customers;
    }
    
    public void setCustomers(Set<Customer> customers) {
        this.customers = customers;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="category")
    public Set<Product> getProducts() {
        return this.products;
    }
    
    public void setProducts(Set<Product> products) {
        this.products = products;
    }




}


