package iti.jets.persistence.model;
// Generated Sep 2, 2024, 5:22:05 PM by Hibernate Tools 6.5.1.Final


import jakarta.persistence.*;

import javax.annotation.processing.Generated;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name="user"
    ,catalog="shomya"
    , uniqueConstraints = {@UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="username")} 
)
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class  User {


     private int id;
     private String name;
     private String username;
     private String password;
     private String email;

    public User() {
    }

    public User(int id, String name, String username, String password, String email) {
       this.id = id;
       this.name = name;
       this.username = username;
       this.password = password;
       this.email = email;
    }
   
     @Id
     @GeneratedValue(strategy = GenerationType.IDENTITY)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }

    
    @Column(name="name", nullable=false, length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="username", unique=true, nullable=false, length=45)
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }

    
    @Column(name="password", nullable=false, length=250)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }

    
    @Column(name="email", unique=true, nullable=false, length=45)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


